version: '3.8'

services:
  one:
    build:
      context: one/
      dockerfile: Dockerfile    
    image: one_image 
    ports:
      - "3001:3000"
    container_name: one    


  two:
    image: nodejs2
    ports:
      - "3002:3000"
    container_name: two    
    build:
			context: two/
			dockerfile: Dockerfile
  three:
    build:
      context: three/
      dockerfile: Dockerfile
    ports:
      - "3003:8000"
    container_name: three

