services:
  one:
    image: node:14-slim
    build:
      context: .
      dockerfile: Dockerfile.one
    working_dir: /app
    volumes:
      - .:/app
    command: npm install

  two:
    image: node:18.16.0-alpine3.17
    build:
      context: ./src
      dockerfile: Dockerfile.two
    working_dir: /opt/app
    volumes:
      - ./src:/opt/app
    command: npm install

  three:
    image: python:3.8-slim
    build:
      context: .
      dockerfile: Dockerfile.three
    working_dir: /app
    volumes:
      - .:/app
    command: touch index.html
